apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: please-payment-web-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store
  target:
    name: please-payment-web-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMTP_USER
      remoteRef:
        key: initial-secret-preset
        property: SMTP_USER
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: initial-secret-preset
        property: SMTP_PASSWORD
    - secretKey: TURNSTILE_SECRET_KEY
      remoteRef:
        key: initial-secret-preset
        property: TURNSTILE_CF_KEY
