
please-payment:
  enabled: true
  nameOverride: please-payment-web

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    image:
      name: pjamenaja/please-payment-web

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 3000
        protocol: TCP
        name: http
