---

envAlias: development
envAliasJob: Development
envGroup: dev

pleasePaymentWebDomain: web-dev.please-payment.local
pleaseProtectWebDomain: web-dev.please-protect.local
pleaseScanWebDomain: web-dev.please-scan.local
devHubsWebDomain: web-dev.dev-hubs.local
