---

envAlias: production
envAliasJob: Production
envGroup: prod

pleasePaymentWebDomain: web-prod.please-payment.local
pleaseProtectWebDomain: web-prod.please-protect.local
pleaseScanWebDomain: web-prod.please-scan.local
